# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a82f64572b0b720b446ac8ef87a2f09174e203566fbfe84ad1165e89a680a240675581130f1946bfd869b216499cc26c31d6763f2458921bd30451a186080abf

test:
  secret_key_base: 39f72299aa29fbc2cc41a0919acb4e90ce7c49defa52650f3e50e133e24e2b15d11c2b89b47f2261b01cb19d64bbecaf5f62d97e31e910f307361ffed3c0f1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
